-keep class com.google.mlkit.** { *; }
-keep class com.google.android.gms.internal.mlkit_vision.** { *; }
-keep class org.tensorflow.lite.** { *; }
-keep class org.tensorflow.lite.gpu.** { *; }
-keep class org.tensorflow.lite.support.** { *; }
